<a href="https://colab.research.google.com/github/UmarKhattab09/DataAnalyticsStuff/blob/main/FeatureEngineering/DataEncoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### DATA ENCODING
- Nominal/OHE
- Label
- Ordinal
- Target Guided Ordinal Encoding

### Nominal/OHE ENCODING
- Each Unique Categorical Value is convereted into a feature.
- Red Green Blue are categorical Feature converting into Numerical Feature

## Disadvatanges
- More Categories, More FEATURES
- Sparse Matrix ----> OverFitting.

In [2]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [3]:
### Create a DataFrame
df = pd.DataFrame({
    "color":['red','blue','green','green','blue','red']
})

In [4]:
encoder = OneHotEncoder()

In [8]:
## Perform Fit and Transform
encoded = encoder.fit_transform(df[['color']]).toarray()

In [10]:
encoded_df = pd.DataFrame(encoded,columns=encoder.get_feature_names_out())
encoded_df

color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         1.0          0.0        0.0
5         0.0          0.0        1.0

In [12]:
encoder.transform([['blue']]).toarray()

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[1., 0., 0.]])

In [13]:
pd.concat([df,encoded_df],axis=1)

color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3  green         0.0          1.0        0.0
4   blue         1.0          0.0        0.0
5    red         0.0          0.0        1.0

In [40]:
##PRACTICE

import seaborn as sns
import numpy as np

df=sns.load_dataset('tips')
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder()
gender = encoder.fit_transform(df[['sex']]).toarray()
gendercols = encoder.get_feature_names_out()
timeofday = encoder.fit_transform(df[['day']]).toarray()
timecols = encoder.get_feature_names_out()
times = encoder.fit_transform(df[['time']]).toarray()
timecols2 = encoder.get_feature_names_out()
smoker = encoder.fit_transform(df[['smoker']]).toarray()
smokercol=encoder.get_feature_names_out()

df2 = pd.DataFrame(np.hstack([gender,timeofday,times,smoker]),
                  columns = list(gendercols) + list(timecols) + list(timecols2) + list(smokercol)
)

In [41]:
df2

sex_Female  sex_Male  day_Fri  day_Sat  day_Sun  day_Thur  time_Dinner  \
0           1.0       0.0      0.0      0.0      1.0       0.0          1.0   
1           0.0       1.0      0.0      0.0      1.0       0.0          1.0   
2           0.0       1.0      0.0      0.0      1.0       0.0          1.0   
3           0.0       1.0      0.0      0.0      1.0       0.0          1.0   
4           1.0       0.0      0.0      0.0      1.0       0.0          1.0   
..          ...       ...      ...      ...      ...       ...          ...   
239         0.0       1.0      0.0      1.0      0.0       0.0          1.0   
240         1.0       0.0      0.0      1.0      0.0       0.0          1.0   
241         0.0       1.0      0.0      1.0      0.0       0.0          1.0   
242         0.0       1.0      0.0      1.0      0.0       0.0          1.0   
243         1.0       0.0      0.0      0.0      0.0       1.0          1.0   

     time_Lunch  smoker_No  smoker_Yes  
0           0.0        1.0         0.0  
1           0.0        1.0         0.0  
2           0.0        1.0         0.0  
3           0.0        1.0         0.0  
4           0.0        1.0         0.0  
..          ...        ...         ...  
239         0.0        1.0         0.0  
240         0.0        0.0         1.0  
241         0.0        0.0         1.0  
242         0.0        1.0         0.0  
243         0.0        1.0         0.0  

[244 rows x 10 columns]

In [42]:
pd.concat([df,df2],axis=1)

total_bill   tip     sex smoker   day    time  size  sex_Female  \
0         16.99  1.01  Female     No   Sun  Dinner     2         1.0   
1         10.34  1.66    Male     No   Sun  Dinner     3         0.0   
2         21.01  3.50    Male     No   Sun  Dinner     3         0.0   
3         23.68  3.31    Male     No   Sun  Dinner     2         0.0   
4         24.59  3.61  Female     No   Sun  Dinner     4         1.0   
..          ...   ...     ...    ...   ...     ...   ...         ...   
239       29.03  5.92    Male     No   Sat  Dinner     3         0.0   
240       27.18  2.00  Female    Yes   Sat  Dinner     2         1.0   
241       22.67  2.00    Male    Yes   Sat  Dinner     2         0.0   
242       17.82  1.75    Male     No   Sat  Dinner     2         0.0   
243       18.78  3.00  Female     No  Thur  Dinner     2         1.0   

     sex_Male  day_Fri  day_Sat  day_Sun  day_Thur  time_Dinner  time_Lunch  \
0         0.0      0.0      0.0      1.0       0.0          1.0         0.0   
1         1.0      0.0      0.0      1.0       0.0          1.0         0.0   
2         1.0      0.0      0.0      1.0       0.0          1.0         0.0   
3         1.0      0.0      0.0      1.0       0.0          1.0         0.0   
4         0.0      0.0      0.0      1.0       0.0          1.0         0.0   
..        ...      ...      ...      ...       ...          ...         ...   
239       1.0      0.0      1.0      0.0       0.0          1.0         0.0   
240       0.0      0.0      1.0      0.0       0.0          1.0         0.0   
241       1.0      0.0      1.0      0.0       0.0          1.0         0.0   
242       1.0      0.0      1.0      0.0       0.0          1.0         0.0   
243       0.0      0.0      0.0      0.0       1.0          1.0         0.0   

     smoker_No  smoker_Yes  
0          1.0         0.0  
1          1.0         0.0  
2          1.0         0.0  
3          1.0         0.0  
4          1.0         0.0  
..         ...         ...  
239        1.0         0.0  
240        0.0         1.0  
241        0.0         1.0  
242        1.0         0.0  
243        1.0         0.0  

[244 rows x 17 columns]

### Label Encoding
- Assign Unique Value to each categories

Disadvantages
- Assigning Label creates rank that effect the ML model

In [44]:
from sklearn.preprocessing import LabelEncoder
### Create a DataFrame
df = pd.DataFrame({
    "color":['red','blue','green','green','blue','red']
})

labelencoder = LabelEncoder()
labelencoder.fit_transform(df[['color']])

/usr/local/lib/python3.11/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2, 0, 1, 1, 0, 2])

In [45]:
labelencoder.transform([['green']])

/usr/local/lib/python3.11/dist-packages/sklearn/preprocessing/_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


array([1])

### Ordinal Encoding
- Categorical Data that requires ranking

for example Education Completed. Bachelors,College,Graduate,PHD

In [46]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder
df = pd.DataFrame({
    'size':['small','medium','large','medium','small','large']
})

In [50]:
### Create a Instance of OrdinalEncoder and then fit_transform
encoder = OrdinalEncoder(categories=[['small','medium','large']]) ## Rank 0 --- > Small, 1--> Medium, 2--->Large

In [51]:
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

### Target Guided Ordinal Encoding
- Converting Categorical Feature into numerical by taking the mean of the of the target belonging to the same categorical Feature

In [57]:
df = pd.DataFrame({
    'city':['NewYork','Japan','Italy','NewYork','Pakistan','Iran'] ,
    'price':[200,150,300,250,180,320]
})

In [64]:
mean_price=df.groupby('city')['price'].mean().to_dict()
df['cityencoded']=df['city'].map(mean_price)

In [65]:
df

city  price  cityencoded
0   NewYork    200        225.0
1     Japan    150        150.0
2     Italy    300        300.0
3   NewYork    250        225.0
4  Pakistan    180        180.0
5      Iran    320        320.0

In [66]:
df[['city','cityencoded']]

city  cityencoded
0   NewYork        225.0
1     Japan        150.0
2     Italy        300.0
3   NewYork        225.0
4  Pakistan        180.0
5      Iran        320.0